embed.add_field(name="1", value="Minecraft", inline=False)
embed.add_field(name="2", value="Aragami", inline=False)
embed.add_field(name="3", value="Among Us", inline=False)
embed.add_field(name="4", value="Dota2", inline=False)
embed.add_field(name="5", value="Quiz Musicale", inline=False)
#embed.add_field(name="6", value="", inline=False)
#embed.add_field(name="7", value="", inline=False)
#embed.add_field(name="8", value="", inline=False)
#embed.add_field(name="9", value="", inline=False)
embed.add_field(name="Istruzioni", value="Aggiungi una reazione con un numero per votare!", inline=False)
