#Update Changelog Page [1]
embed.set_author(name="Simpy-Bot", icon_url="https://discordtemplates.me/static/img/icon.png")
embed.add_field(name="[09/10/20] - Inizio del Changelog di Simpy", value="Contiene principalmente risposte a messaggi, qualche comando è implementato come conseguenza di un messaggio.", inline=False)
embed.add_field(name="[09/10/20] - Versione 1.1", value="Simpy ha raggiunto la versione Beta 1.1!", inline=False)
embed.add_field(name="[09/10/20] - Conseguenze Warn", value="Sono state rivalutate le conseguenze delle segnalazioni.\n(Per saperne di più digita in chat $help-warn)", inline=False)
embed.add_field(name="[11/10/20] - Reazioni Simpy", value="Da adesso Simpy reagisce a più messaggi della chat, tra cui:'La cacca', 'Ma la cacca', 'Lmao', 'Come stai Simpy?', 'Simpy ti odio'.", inline=False)
embed.add_field(name="[13/10/20] - Comandi Help", value="Da adesso l'output dei comandi $help verrà inviato dal bot nei messaggi direct dell'esecutore del comando.", inline=False)
embed.add_field(name="[19/10/20] - Comando Purge", value="Aggiunto il comando $purge... per eliminare i messaggi in stock da 1, 5 e 10. Questo comando è riservato esclusivamente agli admin.", inline=False)
embed.add_field(name="[20/10/20] - Permessi Comandi", value="Da adesso i comandi elevati sono eseguibili solo da Admin e membri fidati.", inline=False)
embed.add_field(name="[20/10/20] - Comando Campbuddy", value="Aggiunto il comando $campbuddy.", inline=False )
embed.add_field(name="[21/10/20] - Comando Campbuddy", value="Aggiunti 13 personaggi al comando.", inline=False)
embed.add_field(name="[23/10/20] - Comando Blacklol", value="Aggiunto il comando $blacklol.", inline=False)
embed.add_field(name="[30/10/20] - Comando Blacklol", value="Aggiunte 25 nuove risposte al comando.", inline=False)
embed.add_field(name="[30/10/20] - Comando Stream", value="Aggiunto il comando $stream.", inline=False)
embed.add_field(name="[30/10/20] - Aggiornamento Comandi", value="Da adesso i comandi $update e $stream potranno essere aggiornati senza dover resettare Simpy.", inline=False)
embed.add_field(name="[30/10/20] - Reazioni Simpy", value="Adesso Simpy reagirà anche ai messaggi 'Hey Simpy', 'Simpy fammi un caffè', 'Andiamo a bruciargli la casa', 'Simpy esplodi', 'Grazie Simpy'.", inline=False)
embed.add_field(name="[04/11/20] - Comando Inspirobot", value="Aggiunto il comando $inspireme.", inline=False)
embed.add_field(name="[09/11/20] - Ottimizzazione Reazioni", value="Da adesso Simpy reagirà ai messaggi indipendentemente dalla posizione in cui si trovano le parole-trigger.", inline=False)
embed.add_field(name="[10/11/20] - Versione 1.2", value="Simpy ha raggiunto la versione Beta 1.2!", inline=False)
embed.add_field(name="[10/11/20] - Migrazione Codice", value="Iniziata la migrazione del codice, potrebbero derivarne malfunzionamenti.", inline=False)
embed.add_field(name="[13/11/20] - Status In-Game", value="Da adesso Simpy avrà uno status in-game che camnierà ogni minuto.", inline=False)
embed.add_field(name="[13/11/20] - Sondaggi", value="Aggiunto il comando $survey, per creare un sondaggio.", inline=False)
embed.add_field(name="[20/11/20] - Blacklol", value="Aggiunte 5 battute.", inline=False)
embed.add_field(name="[05/12/20] - Supporto Vocale", value="Aggiunta la funzione vocale di Simpy; da adesso potrà unirsi alle conversazioni nei canali vocali e riprodurre tracce audio su richiesta. Al momento l'unico canale vocale supportato è #Generale.", inline=False)
embed.add_field(name="[05/12/20] - Soundboard", value="Aggiunta una serie di comandi per richiedere a Simpy di riprodurre file sonori. Per saperne di più scrivi $soundboard in chat.", inline=False)
embed.add_field(name="[10/12/20] - Migrazione Codice", value="La migrazione del codice è completata! Da adesso tutti i comandi di Simpy utilizzeranno il prefisso $.", inline=False)
embed.add_field(name="[11/12/20] - Comando Ping", value="Aggiunto il comando $ping, per mostrare i ping di latenza del bot.", inline=False)
