#Update Changelog Page [3]
embed.set_author(name="Simpy-Bot", icon_url="https://discordtemplates.me/static/img/icon.png")
embed.add_field(name="[21/01/21] - Comando Stream", value="Il comando $stream è stato rimosso dallo script per inutilizzo e impraticità.", inline=False)
embed.add_field(name="[21/01/21] - Linee di Codice", value="Simpy ha ragginto 1000 linee di codice!", inline=False)
embed.add_field(name="[21/01/21] - Permessi Comandi", value="Impostati correttamente i permessi dei comandi.", inline=False)
embed.add_field(name="[22/01/21] - Comandi Ban e Kick", value="Aggiunti i comandi $ban e $kick.", inline=False)
embed.add_field(name="[27/01/21] - Comando Wiki", value="Aggiunto il comando $wiki, per effettuare ricerche su Wikipedia (ancora in fase di test).", inline=False)
embed.add_field(name="[28/01/21] - Comando Cromo", value="Aggiornato il comando $cromo, da adesso può essere seguito da un @tag per sapere il numero di cromosomi della persona taggata.", inline=False)
embed.add_field(name="[28/01/21] - Comando Dicebet", value="Aggiunto il comando $dicebet.", inline=False)
embed.add_field(name="[28/01/21] - Versione 2.2", value="Simpy ha raggiunto la versione Beta 2.2!", inline=False)
embed.add_field(name="[30/01/21] - Comando Dicebet", value="Bilanciate le vincite del comando.", inline=False)
embed.add_field(name="[31/01/21] - Comando Wiki", value="Migliorato il comando $wiki, da adesso cliccando sul titolo dell'embed si potrà raggiungere la pagine ricercata sul sito di Wikipedia per ulteriori info.", inline=False)
embed.add_field(name="[06/02/21] - Comando Inno", value="Aggiunto il comando $inno, per ascoltare l'ultima versione dell'inno di Gordy.", inline=False)
embed.add_field(name="[11/02/21] - Temp-Mute Automatico", value="D'ora in avanti le persone che scriveranno messaggi contenenti frasi o parole proibite verranno temp-mutate per 30 secondi, vedi $helpme per ulteriori informazioni.", inline=False)
embed.add_field(name="[14/02/21] - Risposte ai Messaggi", value="Ottimizzate le risposte ai comandi, potrebbero manifestarsi degli errori.", inline=False)
embed.add_field(name="[14/02/21] - Comando Logout", value="Riscritto il comando $logout: rimossa la password, la richiesta di shutdown dovrà essere confermata via terminale dall'host.", inline=False)
embed.add_field(name="[17/02/21] - Comando Salv-", value="Aggiunto il comando $salv, invierà una parola casuale che comincia con salv-.", inline=False)
embed.add_field(name="[21/02/21] - Comando Update", value="Il comando $update d'ora in poi sarà disponibile solo nei DM.", inline=False)
embed.add_field(name="[21/02/21] - Comando Changelog", value="Aggiunto il comando $changelog, che sostituisce il comando $update nei server.", inline=False)
embed.add_field(name="[22/02/21] - Comando Palla 8", value="Aggiunto il comando $eight_ball ($8), che darà una risposta alle tue domande.", inline=False)
embed.add_field(name="[25/02/21] - Comando Changelog", value="Aggiornato e migliorato il comando $changelog.", inline=False)
embed.add_field(name="[25/02/21] - Comando Avatar", value="Aggiunto il comando $avatar, per mostrare l'avatar di un membro del server.", inline=False)
embed.add_field(name="[25/02/21] - Voice Update", value="Iniziato il Mega Voice Update, durante lo sviluppo della nuova estensione Simpy continuerà ad operare con la vecchia versione del modulo Voice.", inline=False)
embed.add_field(name="[25/02/21] - Voice Update", value="Migliorati i comandi $stop, $pause, $resume.", inline=False)
embed.add_field(name="[27/02/21] - Comando Play", value="Fixato e aggiornato il comando $play: Può essere seguito da un url di Youtube o da il titolo della canzone che si vuole ascoltare. Eliminato il comando $song e i suoi comandi figli.", inline=False)
embed.add_field(name="[27/02/21] - Comandi Join e JoinMe", value="Aggiunto il comando $joinme, che connetterà Simpy al canale vocale in a cui sei collegato. Se Simpy è già connesso ad un canale si spostera in quello in cui ti trovi.", inline=False)
embed.add_field(name="[27/02/21] - Voice Update", value="A causa dell'annuncio di un'aggiornamento alla sezione vocale di Discord.py, il Mega Voice Update è satto sospeso.", inline=False)
