#Update Changelog Page [2]
embed.set_author(name="Simpy-Bot", icon_url="https://discordtemplates.me/static/img/icon.png")
embed.add_field(name="[11/12/20] - Comando Flip", value="Aggiunto il comando $flip, che emula il lancio di una moneta.", inline=False)
embed.add_field(name="[11/12/20] - Comando Logout", value="Aggiunto il comando $logout, utilizzabile unicamente dal proprietario del bot.", inline=False)
embed.add_field(name="[23/12/20] - Comando Echo", value="Aggiunto il comando $echo, che fa ripetere a Simpy la frase scritta successivamente.", inline=False)
embed.add_field(name="[23/12/20] - Comando Helpcom", value="Ottimizzato il comando $helpcom, in elaborazione la classificazione dei comandi normali.", inline=False)
embed.add_field(name="[24/12/20] - Versione 1.3", value="Simpy ha raggiunto la versione Beta 1.3!", inline=False)
embed.add_field(name="[24/12/20] - Banca dei Cromosomi", value="Creata la banca dei cromosomi e aggiunti nuovi comandi ad essa relativi. Da adesso ogni membro del server avrà dei cromosomi virtuali collegati. Per aggiungere dei cromosomi ad un utente usa il comando $addc.", inline=False)
embed.add_field(name="[24/12/20] - Comando Addc", value="Aggiornato il comando $addc, dopo il comando ed il tag si potrà specificare il numero di cromosomi da aggiungere, di default è 1.", inline=False)
embed.add_field(name="[24/12/20] - Comando MyCromo", value="Aggiunto il comando $mycromo, che mostra il numero di cromosomi che si possiede.", inline=False)
embed.add_field(name="[26/12/20] - Comando Cromo", value="Cambiato il nome del comando $mycromo > $cromo. Aggiornato l'embed di risposta, aggiungendo i cromosomi reali e i cromosomi totali.", inline=False)
embed.add_field(name="[27/12/20] - Supporto Vocale dei Canali", value="Da adesso quando si utilizza il comando $join è possibile specificare il canale vocale al quale si deve connettere.", inline=False)
embed.add_field(name="[30/12/20] - Comando Tris a due Giocatori", value="Aggiunta la possibilità di giocare a Tris a due Giocatori. $helpcom per sapere di più sui comandi da utilizzare per giocare.", inline=False)
embed.add_field(name="[31/12/20] - Comando Dado", value="Aggiunto il comando $dado.", inline=False)
embed.add_field(name="[31/12/20] - Aggiornamento Comando Help", value="Da adesso il comando $helpcom potrà essere aggiornato senza dover resettare Simpy.", inline=False)
embed.add_field(name="[05/01/21] - Comando Soon", value="Aggiunto il comando $soon, che mostra le funzionalità che verranno aggiunte a Simpy in futuro.", inline=False)
embed.add_field(name="[05/01/21] - Comando Esse", value="Aggiunto il comando $esse, mostra uno scioglilingua randomico contenente tante esse.", inline=False)
embed.add_field(name="[05/01/21] - Comando Giveaway", value="Aggiunto il comando $giveaway, per creare giveaway di cromosomi con vincitore casuale.", inline=False)
embed.add_field(name="[08/01/21] - Comando Blacklol", value="Ottimizzato il comando blacklol.", inline=False)
embed.add_field(name="[08/01/21] - Versione 2.0", value="Simpy ha raggiunto la versione Beta 2.0!", inline=False)
embed.add_field(name="[08/01/21] - Migrazione Codice", value="Iniziata la riscrittura utilizzando i Cogs. Il processo potrebbe richiedere molto tempo, nel frattempo Simpy continuerà ad operare online usando la versione 1.3.9, ma non è garantita la piena funzione dei comandi.", inline=False)
embed.add_field(name="[12/01/21] - Migrazione Codice", value="Finita la riscrittura dei Cogs.", inline=False)
embed.add_field(name="[12/01/21] - Comando Leaderboard", value="Aggiunto il comando $leaderboard, che mostra una lista dei membri del server con più cromosomi.", inline=False)
embed.add_field(name="[13/01/21] - Comando Status", value="Aggiunto il comando $status, che permetterà di cambiare lo status di Simpy (online, idle, offline, invisible) e il Game Status.", inline=False)
embed.add_field(name="[15/01/21] - Comando Slot Machine", value="Aggiunto il comando $slot, per tentare di vincere dei cromosomi alla Slot Machine. Controlla la sezione 'Cromosomi' del comando $helpcom per scoprire i premi in palio e i prezzi per ogni tiro.", inline=False)
embed.add_field(name="[15/01/21] - Comando Choose", value="Aggiunto il comando $choose, che fa una scelta tra varie opzioni date.", inline=False)
embed.add_field(name="[15/01/21] - Comando Reverse", value="Aggiunto il comando $reverse che inverte le lettere del messaggio che segue.", inline=False)
