#Update Changelog Page [4]
embed.set_author(name="Simpy-Bot", icon_url="https://discordtemplates.me/static/img/icon.png")
embed.add_field(name="[27/02/21] - Versione 3.1", value="Simpy ha raggiunto la versione Beta 3.1!", inline=False)
embed.add_field(name="[27/02/21] - Comando Wiki", value="Migliorato il footer nell'embed del comando $wiki, da adesso verrà mostrato il nome di chi ha eseguito il comando e la sua immagine profilo.", inline=False)
embed.add_field(name="[04/03/21] - Comandi Voice", value="Ulteriore revisione ai comandi della sezione voice.", inline=False)
embed.add_field(name="[04/03/21] - Comando Inno", value="Aggiornato il comando $inno, d'ora in poi utilizzando questo comando durante la riproduzione di un altro brano questo si fermerà automaticamente, per dare la precedenza all'inno", inline=False)
embed.add_field(name="[06/03/21] - Correzioni", value="Corrette alcuni errori grammaticali e sintattici nello script.", inline=False)
embed.add_field(name="[07/03/21] - Comando Youtube", value="Aggiunto il comando $youtube, per effettuare una ricerca su youtube.", inline=False)
embed.add_field(name="[08/03/21] - Comando Slot", value="Modificati la quantità cromosomi ottenuti con un triplo e un triplo avocado.", inline=False)
embed.add_field(name="[19/03/21] - Comando Slowmode", value="Aggiunto il comando $slowmode, per gestire la slowmode dei canali testuali.", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
#embed.add_field(name="[]", value="", inline=False)
